services:
  - type: web
    name: adplus
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn plateforme_annonces.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false  # Ã€ configurer manuellement dans le dashboard

