services:
  - type: web
    name: adplus  # Changez ce nom pour personnaliser l'URL : votre-nom.onrender.com
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false  # À configurer manuellement avec votre nom de service ou domaine personnalisé

